#!/bin/bash

sudo modprobe -qr appletb

for tb_dev in /sys/bus/hid/devices/*/input ; do
    tb_dev="${tb_dev%/*}"
    tb_dev="${tb_dev##*/}"
    echo "$tb_dev" | sudo tee /sys/bus/hid/drivers/hid-generic/unbind > /dev/null
done

[[ -e appletb.ko ]] && sudo insmod appletb.ko || sudo modprobe appletb
